# Database configuration for Rails environment (production, development, etc.)

default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: "farmbot_development"
  host: "localhost"
  username: "farmbot"
  password: "password"

# In production, skip the database connection entirely
production:
  <<: *default
  # Skip database connection in production
  database: "farmbot_production" # Placeholder name, can be ignored
  host: <%= ENV['DB_HOST'] || 'localhost' %> # No real DB connection
  username: <%= ENV['DB_USERNAME'] || 'user' %> # No real DB credentials
  password: <%= ENV['DB_PASSWORD'] || 'password' %> # No real DB password
  pool: 0  # Disable connection pooling for production

  # Disable ActiveRecord (optional - needed if skipping ActiveRecord entirely)
  disconnected: true

# If you still want to keep the test environment with minimal setup
test:
  <<: *default
  database: "farmbot_test"
  host: "localhost"
  username: "farmbot"
  password: "password"
