name: Deploy FarmBot Web API (No Database)

on:
  push:
    branches:
      - dev  # Trigger deployment when the dev branch is updated

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Ruby 3.2 for compatibility with i18n and Devise
      - name: Set up Ruby 3.2
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'

      # Step 3: Install dependencies and build the static assets
      - name: Build and Precompile Assets
        run: |
          bundle install
          npm install
          npm run build  # Adjust based on your build process (e.g., "npm run build" for React apps)

      # Step 4: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.0.0
        with:
          branch: gh-pages  # The branch to deploy to
          folder: build  # Folder containing the built static files (adjust as necessary)
          token: ${{ secrets.GITHUB_TOKEN }}
